services:
  difuze-with-kernel:
    build: 
      context: .
      dockerfile: ./difuze-docker-full
    container_name: difuze
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    volumes:
      - /path/to/linux:/difuze/kernel
      - /path/to/difuze/out:/difuze/out
      - /path/to/difuze:/difuze/repo
